### ISSUE TITLE
remove broken link to ecocomDP packages

### ISSUE THREAD

**Issue by twhiteaker** [EDIorg/data-package-best-practices#58]
Link on https://ediorg.github.io/data-package-best-practices/datapackage-design/code-in-edi.html to ecocomDP packages points to https://portal.edirepository.org/nis/simpleSearch, which isn't useful. I suggest just removing the link.

**Comment by mobb** [comment]
@twhiteaker 
the link should have pointed to this stored query: 
http://portal.edirepository.org:80/nis/simpleSearch?defType=edismax&q=ecocomDP&fq=-scope:ecotrends&fq=-scope:lter-landsat*&fl=id,packageid,title,author,organization,pubdate,coordinates&debug=false

Something must have gotten truncated.
can you repair instead of delete?
thanks.
